python PlotIt.py limit LL 
python PlotIt.py limit ML 
python PlotIt.py limit TL 
python PlotIt.py limit MM 
python PlotIt.py limit TM 
python PlotIt.py limit TT 
python PlotIt.py limit LLb 
#python PlotIt.py limit MLb 
python PlotIt.py limit TLb 
python PlotIt.py limit MMb 
python PlotIt.py limit TMb 
python PlotIt.py limit TTb 
