./skimtree mc DoubleMuB.root Mode mass
./skimtree mc DoubleMuC.root Mode mass
./skimtree mc DoubleMuD.root Mode mass
./skimtree mc DYBB1070.root Mode mass
./skimtree mc DYJetsLowMass.root Mode mass
./skimtree mc DYJets.root Mode mass
./skimtree mc GGH15.root Mode mass
./skimtree mc GGH20.root Mode mass
./skimtree mc GGH25.root Mode mass
./skimtree mc GGH30.root Mode mass
./skimtree mc GGH35.root Mode mass
./skimtree mc GGH40.root Mode mass
./skimtree mc GGH45.root Mode mass
./skimtree mc GGH50.root Mode mass
./skimtree mc GGH55.root Mode mass
./skimtree mc GGH60.root Mode mass
./skimtree mc TbarW.root Mode mass
./skimtree mc TChannel.root Mode mass
./skimtree mc TTbar.root Mode mass
./skimtree mc TW.root Mode mass
./skimtree mc WJetsMG.root Mode mass
./skimtree mc WW.root Mode mass
./skimtree mc WZ.root Mode mass
./skimtree mc ZZ.root Mode mass
